### ISSUE TITLE
CN Server Update

### ISSUE THREAD

**Issue by MoYingJi** [an-anime-team/honkers-launcher#47]
The current version of the Chinese Mainland server is 7.6.0, but the launcher has only been updated to 7.5.0

**Comment by Linus-XZX** [comment]
7.6 is now only delivered via miHoYo Launcher, which honkers does not currently have support for.

Do you have another device with a working unified launcher? Downloading the game from there and copying it to replace the current game installation should work, though some manual file twerking may still be required.

**Comment by MoYingJi** [comment]
I downloaded the latest version using miHoYo Launcher, but the honkers launcher caused me to downgrade(Display 'Update') to 7.5.0

**Comment by Linus-XZX** [comment]
That’s a known issue due to how versions are compared in the current implementation, and should be addressed in an upcoming update (the same fix should already be live in the new AAGL release).

When it comes up you **may** need to manually modify the `.version` file to say something like 7.6.0 as well.

**Comment by krypt0nn** [comment]
Must be fixed in https://github.com/an-anime-team/honkers-launcher/pull/48
